spring:
  sql:
    init:
      mode: always
      platform: h2

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    # H2 database configuration.
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./db/user-burse
    username: admin
    password: 123456